# Generated by Django 5.2.6 on 2025-09-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_message_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
