# Generated by Django 5.2.6 on 2025-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_message_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.CharField(blank=True, default="Anonymous", max_length=50),
        ),
    ]
